# Generated by Django 3.2.11 on 2022-01-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('object', models.CharField(max_length=200)),
                ('timestap', models.CharField(max_length=100)),
            ],
        ),
    ]
