# Generated by Django 3.2.11 on 2022-01-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='object',
            new_name='objects_detected',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
